### ISSUE TITLE
Diarization accuracy is terrible!

### ISSUE THREAD

**Issue by cunnie** [blabbertabber/blabbertabber#35]
Diarization accuracy is terrible! @saintbrendan  and I used LIUM+Sphinx4 to diarize a ten-minute conversation between ourselves, and the results were disappointing: it identified 15+ distinct speakers rather than two.

Darin Herle, who posted a similar issue on the [Sphinx4 forums](https://sourceforge.net/p/cmusphinx/discussion/help/thread/cb0b65fa/),  wrote to us and said the following:

> We discovered that the current state of the art, open source speaker diarization tools aren’t quite advanced enough to do what we wanted.
> 
>  They appear to work well for higher quality/low noise, near field, high SNR recordings involving 2 speakers with minimal speech overlap.  When we tried to apply this to a meeting environment (multiple speakers, near and far field, poor audio quality, lots of overlapping speech), our diarization output was poor.  This appears to be simply a limitation of what the tool can do.

Dr. Friedland, however, wasn't so pessimistic:

> LIUM isn't the best tool. It's only the one that is open source. 
> The answer to your question is quite complex and can only be done by taking a close look at your recordings. Then, for your typical conditions, _you need to choose the right methods to pre-process the signal, select the right diarization approach, tune-it and then also post-process the diarization results_.

(italics mine)

**Comment by cunnie** [comment]
Closing. We've been using the Aalto diarizer for the last few months and it has been pretty decent.

**Comment by austingayler** [comment]
@cunnie what's your experience with Aalto been like so far?

**Comment by cunnie** [comment]
It's correct 74% of the time, but that's a sample size of 1 (1 ten-minute conversation with three people).

In other words, I'm pretty pleased with Aalto, but I wish there was a diarizer that was correct 90+% of the time.
