### ISSUE TITLE
any updates on real-time speaker diarization?

### ISSUE THREAD

**Issue by GeorvityLabs** [blabbertabber/blabbertabber#73]
would be great if diarization could be done in real-time.
while user is speaking ,it assigns label (speaker 1 , 2 etc)
so that we get real-time classification of who is speaking.

**Comment by cunnie** [comment]
> would be great if diarization could be done in real-time.

I like that idea!

Unfortunately, I've mothballed the project—I couldn't find a good-enough backend. Maybe things have changed in the last few years, but I doubt I'll pick this up, and if I do it'll probably skip the diarization and instead really on separate audio streams (think Zoom, where you know which person is speaking when).
